### ISSUE TITLE
Default license

### ISSUE THREAD

**Issue by khaosdoctor** [knowledge-club/knowledge-club#1]
Pessoal precisamos pensar qual vai ser a licença padrão @darlanmendonca e @WendellAdriel 

Eu estou usando a GPL3 mas se vocês tiverem outra ideia

**Comment by darlanmendonca** [comment]
me parece bom a gpl3, eh open, e quem usá-la deve manter tal licensa right?

**Comment by khaosdoctor** [comment]
Sim, GPL quem usar tem que passar os mesmos direitos no projeto, não pode alterar a licença, e tem que identificar se o programa foi modificado

**Comment by khaosdoctor** [comment]
Acho que é uma boa, já que o intuito do projeto é ser da comunidade

**Comment by darlanmendonca** [comment]
concordo plenamente!!

**Comment by khaosdoctor** [comment]
Fechou então! GPL será
