### ISSUE TITLE
Default Language

### ISSUE THREAD

**Issue by khaosdoctor** [knowledge-club/knowledge-club#2]
Qual será a lingua que vamos usar pra escrever nossos códigos aqui? Inglês mesmo? E comunicação?

@darlanmendonca @WendellAdriel

**Comment by darlanmendonca** [comment]
qto a comunicação, creio q algo extremamente didático e natural fique bem bacana!! Referência https://woliveiras.com.br/vimparanoobs/, do mano @woliveiras. Se preferirem outro estilo de comunicação mandem umas referências. Eu pessoalmente gosto do estilo do @woliveiras, por tornar agradável um assunto que pode passar a ser tedioso, após algum tempo lendo.

Quanto ao idioma, eu realmente acredito que devamos atingir mais pessoas, usando Inglês, massss, tbm sei que isto será uma grande barreira para novos devs de idioma português, e como o nosso foco deve ser a didática também, acredito que valha a pena o trabalho conjunto pt/en.

Sugiro começarmos por português, e já nos organizarmos quanto a tradução para o Inglês. Óbvio que dá um trabalho dos infernos, mas creio que valha a pena, principalmente a longo prazo (vida útil do projeto).

**Comment by darlanmendonca** [comment]
ou talvez eu steja errado qto ao default, talvez o default adequado seja inglês, e devamos traduzir pra português, uma vez q o padrão é Inglês. Exemplo, short description do repo, deve estar em inglês, uma vez q n da pra traduzir na exibição

**Comment by khaosdoctor** [comment]
Quanto a didática acho que vai de cada um que escreve, na hora de analisar a PR podemos dar umas dicas de didática ou informar se está ok ou dificil de entender.

Quanto a linguagem eu já discordo, acredito que seja melhor padronizar tudo em inglês, e ter uma versão em portugues de cada repo, por exemplo:
- bash/
  - README.md (sumário)
  - content/
    - pt_br/
      - artigos.md
    - en_us/
      - articles.md

Só que teríamos que ter dois sumários também...

**Comment by darlanmendonca** [comment]
sim, qto a didatica é mais um "preocupe-se" em explicar rs, kda um pensa/fala d formas diferentes.
mas pod ser melhorado no proprio code review, ou feito posteriormentes em novas pull request

**Comment by darlanmendonca** [comment]
qto ao idioma, vc citou repos, e no exemplo citou num mesmo repo, tendo arquivos para kda idioma, creio q a sugestao seja deste ultimo right?

**Comment by khaosdoctor** [comment]
Na verdade seria para qualquer repo futuro, para cada linguagem diferente teríamos que ter uma pasta com o nome da linguagem e, dentro, os arquivos naquela lingua, mas com o padrão em ingles, como estamos fazendo ali no bash

**Comment by khaosdoctor** [comment]
Começamos sempre com o ingles, e ai adicionamos a versão em portugues se tiver, colocar o sumário em duas linguas (essa é a parte que me preocupa)

**Comment by darlanmendonca** [comment]
entendi!!

qto ao Readme, ele conterá oq?

**Comment by darlanmendonca** [comment]
pq se ele conter apenas links, estes links podem ser nomes tecnicos, logo n traduzidos, exemplo:

#### javascript
- var, let, const
- strings
- numbers
- arrays
  ...

**Comment by darlanmendonca** [comment]
agora se contiver links c necessidad d tradução, sugiro um readme em inglies, q tenha apenas dois links, sendo portugues (que aponta pra um sumario em pt), e ingles(pra um sumario em ingles)

**Comment by darlanmendonca** [comment]
lembrei agora do link (src msmo apontando pra pt ou en)

**Comment by darlanmendonca** [comment]
voto entao por um readme q seja em inglês, contendo link para sumario.md e outro pra summary.md,

e tbm no readme, mention to contributing.md

ou seja, teríamos dois sumarios e dois arquivos para kda artigo

**Comment by khaosdoctor** [comment]
Acho que teríamos que ter um Readme só, nele teria só o sumário (poderíamos colocar os dois links mesmo se precisar, lado a lado). Mas ninguém poderia editar diretamente o arquivo a não ser quem cuida do repositório, assim evitamos de ter vários arquivos editados em PR separadas

**Comment by darlanmendonca** [comment]
bacana, iria simplificar mais msmo, um readme soh
- var, let, const [english](#), [português](#)

**Comment by darlanmendonca** [comment]
por mim fexou

readme contem o sumário, com titulo de referencia n traduzido, e links para multiplos idiomas

e oq contribuírem, sera um artigo no content/en e/ou content/pt-br

**Comment by khaosdoctor** [comment]
Beleza, vou fechar e abrir um README geral com tudo que a gente já acordou
