### ISSUE TITLE
CONTRIBUTING

### ISSUE THREAD

**Issue by darlanmendonca** [knowledge-club/knowledge-club#3]
Hey guys, we are thinking in how organize contributions.

The target of each repo, is teach/learn continuously. So, I suggest the following organization to all repositories (with your exceptions when is relevant, discuss in self repo, like in [bash](https://github.com/knowledge-club/bash/issues/13))
# draft in portuguese

Gostou do conteúdo e quer contribuir? Adoraríamos sua ajuda, assim construímos conteúdos realmente relevantes, útil para quem está começando, e também para nós que continuamente estamos sempre aprendendo.

Nosso objetivo é listar coisas de forma:
- didática
- com exemplos
- e com atividades quando possível

Didática e exemplos ajudam a entender, que é o mais importante.
Atividades ajudam a fixar o conteúdo em mente, se não não adianta :D.
### Como contribuir

A fim de facilitar contribuições e revisões, precisamos nos organizar. Juntos definimos alguns processos para contribuirmos de forma fácil e evitando possíveis erros:
1. Dê fork no projeto
2. Crie uma branch, para adicionar sua contribuição
3. Faça um tipo apenas de contribuição por vez
4. Faça uma pull request

Por um tipo apenas quero dizer, evite adicionar conteúdos de assuntos divergentes de uma só vez. Exemplo, vou contribuir com um artigo sobre condicional e loop. Então devem ser dois pull requests, e não apenas um. Isto além de facilitar o code review, também irá evitar conflitos, e facilitar correções necessárias.
### Organização

Quando for adicionar um novo comando, crie um arquivo markdown, exemplo conditionals.md, e em tal arquivo, aborde o mesmo.
No Readme.md listamos apenas os artigos realmente básicos/essenciais para quem está começando. 
Demais artigos, são listados no arquivo summary.md, e ordenados em ordem alfabética.

Ou seja, quando for contribuir com um novo comando
- Crie um arquivo para o mesmo (exemplo: conditionals.md).
- Adicione o link para o mesmo em summary.md, em ordem alfabética.
- Ou adicione no Readme.md se realmente for básico/essencial.

**Comment by khaosdoctor** [comment]
Dá uma olhada na nessa aqui https://github.com/knowledge-club/bash/pull/14/ Eu adicionei uns comentários na versão em ingles, mas posso adicionar aqui a versão em portugues também

**Comment by khaosdoctor** [comment]
Adicionei no #5 pode dar uma olhada, se for isso já criamos como padrão aqui.

Vale a pena mencionar os exercicios?

**Comment by darlanmendonca** [comment]
eu acredito q sim, mass no futuro, vamos amadurecer a idéia

por exemplo, to qrendo exercicios d javascript no codewars

mas talvez a gnte encontre kras melhores ainda, ou n, rs, vamos deixar isto para o futuro, por hora eh melhor do jeito q montamos no bash

**Comment by khaosdoctor** [comment]
Certo, vamos esquecer os Ex por enquanto
