### ISSUE TITLE
Ruby basics

### ISSUE THREAD

**Issue by odineiramone** [knowledge-club/knowledge-club#4]
Me proponho a fazer um basics de ruby mas gostaria de saber se seria relevante. Na internet existem vários tutoriais bem curtos de Ruby como o Ruby em 20 Minutos e o Try Ruby (Code School) então, não sei se um ruby-basics aqui no knowledge-club seria relevante

**Comment by khaosdoctor** [comment]
Show! Vou adicionar você é criar o repo pra você poder começar ;D, só estamos definindo algumas coisas de padronização, assim que terminarmos já vamos deixar tudo nos moldes

**Comment by odineiramone** [comment]
Opa! Obrigado @khaosdoctor! Vou ler certinho sobre como contribuir e criarei alguns guias para ruby!

**Comment by khaosdoctor** [comment]
;) O arquivo de contribuição padrão está no #5 e em breve vou adicionar um README aqui com as direções iniciais

**Comment by darlanmendonca** [comment]
Yeahh, bem veindo @OdineiRibeiro !!

No repo, pod fazer oq desejares, eu pessoalmente pretendo nos repos, diferente do bash, q acaba sendo uma lista, kda um ensinar mesmo desde o básico, por exemplo, 

no javascript explicar tim tim por timtim a syntax, e lógica (es6, es6, ifs, switch, loop, array methods, e por awe vai)

no de angular, explicar a arquitetura, single responsability, e pra que serve kda component, um controller, um service, um factory, um filter, uma diretiva, etc

qto ao do Ruby q vc propos não sei exatamente o q pretendes, já q temos o antigo bash-basics q segue um formato um tanto diferente, independente do q for, pod mandar bala, rs

eh mais para nos alinharmos bem :D

**Comment by odineiramone** [comment]
@darlanmendonca e @khaosdoctor, eu pretendo também ensinar coisas básicas como instalar ruby em OS's diferentes, usar o interpretador de ruby no terminal, alguns "truques" da linguagem (Sintax Sugar) e criar um programa num arquivo _.rb_

Seriam coisas de nível iniciante e médio (até porque eu não estou além disso) para quem está començando mesmo

**Comment by darlanmendonca** [comment]
da hora!! 
chama d 'ruby' apenas, c o tempo o repo vai crescendo c contribuições, essa é a meta :D

**Comment by odineiramone** [comment]
Tranquilo @darlanmendonca! Obrigado, assim que o repo for criado já começo a criar alguns guias!

**Comment by darlanmendonca** [comment]
nóis q agradece, td mundo ganha :D

**Comment by khaosdoctor** [comment]
@OdineiRibeiro Repo Criado! Invite enviado! Só aceitar

**Comment by odineiramone** [comment]
Obrigado @khaosdoctor! Aceitei o invite e já vou começar a criar o conteúdo! Neste caso, é necessário criar um PR para o conteúdo que eu vou colocar ou, como sou eu que vou começar a adicionar coisas de ruby lá, é só subir direto?

**Comment by khaosdoctor** [comment]
Pode subir direto, você será o moderador desse repo, então vc vai ser o responsável por manter no padrão que estamos definindo lá dentro, aceitar PRs e etc
