### ISSUE TITLE
Final Default

### ISSUE THREAD

**Issue by khaosdoctor** [knowledge-club/knowledge-club#7]
I believe we have agreed to a final default template right @darlanmendonca @WendellAdriel @OdineiRibeiro? Let's use https://github.com/knowledge-club/javascript as base to all other repos we create from now on.

What do you guys think?

**Comment by odineiramone** [comment]
Yep! We can use the javascript repo as base to another repos!

**Comment by khaosdoctor** [comment]
Awesome! Now you can begin the Ruby basics!

**Comment by darlanmendonca** [comment]
I agree, future modifications os special exceptions maybe appear, but so far, it seems a great way

thanks guys!!

**Comment by khaosdoctor** [comment]
Ok then! Let's use this as our primary base default for all repos, will add this to the README and rules
